version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-S1021"
        - "-ST1000"
